import { Deal, ThesisConfig, AIDetectionReport } from './types';

const fluxAIDetection: AIDetectionReport = {
  overallScore: 18,
  sections: [
    { name: 'Executive Summary', score: 12, flag: null },
    { name: 'Problem / Solution', score: 15, flag: null },
    { name: 'Market Sizing', score: 38, flag: 'Standard TAM/SAM/SOM framing with Gartner citation — common AI boilerplate' },
    { name: 'Traction', score: 8, flag: null },
    { name: 'Team', score: 11, flag: null },
  ],
  flaggedExcerpts: [
    {
      text: 'The global corporate expense management software market is estimated at $28B, with a serviceable addressable market of $6.4B targeting mid-market enterprises.',
      section: 'Market Sizing',
      reason: 'Generic market framing with round numbers — consistent with AI-assisted market slide generation.',
    },
  ],
  analystNote: 'Deck reads as human-authored. Market sizing section shows minor AI-assist markers common in modern pitch decks. Overall narrative is specific and non-generic.',
};

const harbrAIDetection: AIDetectionReport = {
  overallScore: 34,
  sections: [
    { name: 'Executive Summary', score: 28, flag: 'Generic sustainability language' },
    { name: 'Problem / Solution', score: 42, flag: 'Problem statement uses common AI phrasing patterns' },
    { name: 'Market Sizing', score: 51, flag: 'BloombergNEF citation without specific report anchor' },
    { name: 'Traction', score: 14, flag: null },
    { name: 'Team', score: 19, flag: null },
  ],
  flaggedExcerpts: [
    {
      text: 'Mid-market manufacturers face increasing regulatory pressure to report Scope 1, 2, and 3 emissions but lack the technical infrastructure and expertise to do so accurately or at scale.',
      section: 'Problem / Solution',
      reason: 'Sentence structure and phrasing ("lack the technical infrastructure and expertise") is a recurring AI generation pattern in climate tech decks.',
    },
    {
      text: 'Harbr integrates directly with operational data systems (ERP, IoT sensors, supply chain APIs) to calculate emissions in real time.',
      section: 'Problem / Solution',
      reason: 'Enumerated tech stack ("ERP, IoT sensors, supply chain APIs") without specificity is an AI content marker.',
    },
  ],
  analystNote: 'Moderate AI-assist markers in problem framing and market sizing. Traction and team sections appear human-authored. Likely used AI to polish the narrative layer over human-sourced data.',
};

const tempoAIDetection: AIDetectionReport = {
  overallScore: 62,
  sections: [
    { name: 'Executive Summary', score: 71, flag: 'High generic language density' },
    { name: 'Problem / Solution', score: 68, flag: 'Textbook problem-solution framing' },
    { name: 'Market Sizing', score: 74, flag: 'Broad market claim without SAM/SOM — AI filler pattern' },
    { name: 'Traction', score: 29, flag: null },
    { name: 'Team', score: 44, flag: 'Bio reads as AI-polished' },
  ],
  flaggedExcerpts: [
    {
      text: 'Outpatient mental health clinics lose an estimated 25% of scheduled appointments to no-shows and cancellations.',
      section: 'Problem / Solution',
      reason: 'Precise-sounding statistic ("estimated 25%") without attribution is a common AI fabrication pattern.',
    },
    {
      text: 'Tempo provides a purpose-built scheduling and waitlist management platform for mental health clinics, with automated reminders, intelligent waitlist backfill, and insurance eligibility verification integrated into the booking flow.',
      section: 'Problem / Solution',
      reason: 'Feature list structure with "intelligent" qualifier and run-on enumeration is a strong AI generation marker.',
    },
    {
      text: 'The behavioral health market represents a $12B opportunity poised for disruption.',
      section: 'Market Sizing',
      reason: '"Poised for disruption" is flagged as an AI-generated cliché with 94% frequency in AI-written pitch summaries.',
    },
  ],
  analystNote: 'Significant AI generation markers throughout. Problem and solution sections show textbook AI structure. The 25% no-show statistic lacks attribution and may be fabricated. Recommend asking founder for source material.',
};

const conduitAIDetection: AIDetectionReport = {
  overallScore: 8,
  sections: [
    { name: 'Executive Summary', score: 6, flag: null },
    { name: 'Problem / Solution', score: 9, flag: null },
    { name: 'Market Sizing', score: 14, flag: null },
    { name: 'Traction', score: 5, flag: null },
    { name: 'Team', score: 7, flag: null },
  ],
  flaggedExcerpts: [],
  analystNote: 'No meaningful AI generation markers. Deck reads as hand-authored by operators who know this space deeply. Traction data is specific and internally consistent. One of the lowest AI scores seen this quarter.',
};

const canopyAIDetection: AIDetectionReport = {
  overallScore: 71,
  sections: [
    { name: 'Executive Summary', score: 78, flag: 'Generic DTC narrative' },
    { name: 'Problem / Solution', score: 82, flag: 'Aspirational consumer language, low specificity' },
    { name: 'Market Sizing', score: 69, flag: 'Unsourced TAM claim' },
    { name: 'Traction', score: 34, flag: null },
    { name: 'Team', score: 61, flag: 'Bio bullet points match AI-generation formatting' },
  ],
  flaggedExcerpts: [
    {
      text: 'Urban consumers lack access to fresh, locally grown produce and have limited space for traditional gardening. Existing hydroponic kits are expensive, complex to maintain, and require horticultural expertise.',
      section: 'Problem / Solution',
      reason: 'Consumer problem framing with three-part structure ("expensive, complex to maintain, and require") is a high-confidence AI generation signal.',
    },
    {
      text: 'Canopy is redefining the relationship between people and food by making sustainable, home-grown produce accessible to everyone.',
      section: 'Executive Summary',
      reason: '"Redefining the relationship" is flagged in 89% of AI-generated consumer pitch decks analyzed.',
    },
    {
      text: 'The indoor gardening and urban agriculture market represents an $8B opportunity growing at 12% CAGR.',
      section: 'Market Sizing',
      reason: 'Unsourced growth rate with two decimal precision is a known AI fabrication pattern in market sizing slides.',
    },
  ],
  analystNote: 'High AI generation confidence. Problem statement, executive summary, and market sizing all exhibit strong AI authorship markers. Traction section (Kickstarter numbers) appears human-sourced. Recommend treating narrative claims skeptically.',
};

export const mockDeals: Deal[] = [
  {
    id: 'deal-flux-001',
    analystId: 'alex@meridiancap.com',
    companyName: 'Flux',
    oneLiner: 'AI-powered expense management for distributed finance teams',
    stage: 'Seed',
    sector: 'B2B SaaS',
    geography: 'New York, NY',
    overallThesisScore: 8.2,
    pipelineStatus: 'under_review',
    analystNotes: 'Strong traction numbers. Need to validate CAC data from founders. Schedule call with VP of Finance at one of their enterprise customers.',
    memoContent: null,
    aiDetection: fluxAIDetection,
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-08T14:30:00Z',
    analysis: {
      companyName: 'Flux',
      oneLiner: 'AI-powered expense management for distributed finance teams',
      problem: 'Enterprise finance teams managing distributed workforces face significant challenges with expense tracking, approval workflows, and real-time visibility into spending. Current solutions require manual reconciliation and lack intelligent categorization.',
      solution: 'Flux provides an AI-driven expense management platform that automates categorization, flags policy violations in real time, and integrates natively with major ERP systems to eliminate month-end reconciliation.',
      businessModel: 'SaaS subscription, tiered by seat count. Enterprise plans include custom integrations and dedicated support. Average contract value of $42K ARR.',
      stage: 'Seed',
      sector: 'B2B SaaS',
      geography: 'New York, NY',
      founded: '2023',
      website: 'fluxfinance.io',
      market: {
        tam: '$28B',
        sam: '$6.4B',
        som: '$320M',
        framing: 'Company targets mid-market to enterprise segment with 200-5,000 employees, citing Gartner data on corporate expense software spend.',
      },
      traction: [
        { metric: 'MRR', value: '$180K' },
        { metric: 'ARR', value: '$2.16M' },
        { metric: 'YoY Growth', value: '340%' },
        { metric: 'Enterprise Customers', value: '42' },
        { metric: 'NPS', value: '71' },
        { metric: 'Churn Rate', value: '1.8%/mo' },
      ],
      team: [
        { name: 'Sarah Kim', role: 'CEO & Co-founder', background: 'Former VP Finance at Brex; 8 years in fintech, previously led product at Ramp.' },
        { name: 'Marcus Webb', role: 'CTO & Co-founder', background: 'Ex-Staff Engineer at Stripe; built expense reconciliation infrastructure serving 50K+ merchants.' },
        { name: 'Priya Nair', role: 'VP Sales', background: 'Former enterprise sales lead at Expensify, closed $12M in ARR over 3 years.' },
      ],
      askingAmount: '$3M',
      valuation: '$18M pre-money',
      redFlags: [
        { headline: 'No stated CAC or payback period', detail: 'Deck omits customer acquisition cost and payback period data, making unit economics difficult to assess.', severity: 'medium' },
      ],
      rawHighlights: [
        '340% YoY growth with 42 enterprise customers signals strong PMF',
        'Founding team has direct domain expertise at category leaders (Brex, Stripe)',
        'Low monthly churn at 1.8% suggests sticky product',
        'CAC and payback period not disclosed — key gap in unit economics story',
        '$28B TAM supported by third-party Gartner data',
        'Native ERP integrations provide meaningful switching costs',
      ],
    },
    thesisScores: [
      { criterion: 'Market Size', score: 9, reason: 'Company cites $28B TAM with third-party Gartner source; credibly sized for enterprise fintech.', weight: 20 },
      { criterion: 'Team Strength', score: 9, reason: 'Both founders have direct prior-company experience at Brex and Stripe — top tier domain fit.', weight: 25 },
      { criterion: 'Traction', score: 8, reason: '$180K MRR with 340% YoY growth and sub-2% churn is strong for Seed stage.', weight: 20 },
      { criterion: 'Stage Fit', score: 8, reason: 'Seed stage at $2.16M ARR run rate aligns well with fund mandate.', weight: 20 },
      { criterion: 'Sector Match', score: 7, reason: 'B2B SaaS within fintech is a primary thesis vertical.', weight: 15 },
    ],
    redFlags: [
      { headline: 'No stated CAC or payback period', detail: 'Deck omits customer acquisition cost and payback period data, making unit economics difficult to assess.', severity: 'medium' },
    ],
  },
  {
    id: 'deal-harbr-002',
    analystId: 'alex@meridiancap.com',
    companyName: 'Harbr',
    oneLiner: 'Real-time carbon accounting platform for mid-market manufacturers',
    stage: 'Series A',
    sector: 'Climate Tech',
    geography: 'Austin, TX',
    overallThesisScore: 7.6,
    pipelineStatus: 'meeting_scheduled',
    analystNotes: 'Partner meeting Thursday. Prepare questions on enterprise contract structure and revenue recognition.',
    memoContent: null,
    aiDetection: harbrAIDetection,
    createdAt: '2026-04-22T11:00:00Z',
    updatedAt: '2026-05-07T09:00:00Z',
    analysis: {
      companyName: 'Harbr',
      oneLiner: 'Real-time carbon accounting platform for mid-market manufacturers',
      problem: 'Mid-market manufacturers face increasing regulatory pressure to report Scope 1, 2, and 3 emissions but lack the technical infrastructure and expertise to do so accurately or at scale.',
      solution: 'Harbr integrates directly with operational data systems (ERP, IoT sensors, supply chain APIs) to calculate emissions in real time, generate audit-ready compliance reports, and benchmark against industry peers.',
      businessModel: 'Annual enterprise SaaS contracts. Revenue currently split 70% software, 30% implementation services. Plans to reduce services revenue as product matures.',
      stage: 'Series A',
      sector: 'Climate Tech',
      geography: 'Austin, TX',
      founded: '2022',
      website: 'harbr.io',
      market: {
        tam: '$18B',
        sam: '$4.2B',
        som: '$210M',
        framing: 'Targets manufacturers with $50M–$2B in annual revenue in North America and Europe, citing BloombergNEF market analysis.',
      },
      traction: [
        { metric: 'ARR', value: '$420K' },
        { metric: 'Customers', value: '18' },
        { metric: 'Signed LOIs', value: '3' },
        { metric: 'Avg Contract Value', value: '$23K' },
        { metric: 'Implementation Revenue', value: '$180K' },
      ],
      team: [
        { name: 'David Park', role: 'CEO & Co-founder', background: 'Former sustainability director at Honeywell; 10 years in industrial decarbonization.' },
        { name: 'Elena Vasquez', role: 'CTO & Co-founder', background: 'Ex-senior engineer at Palantir, specialized in industrial data infrastructure.' },
        { name: 'Thomas Reid', role: 'VP Customer Success', background: 'Former account executive at Salesforce, 5 years in enterprise SaaS.' },
      ],
      askingAmount: '$8M',
      valuation: '$32M pre-money',
      redFlags: [
        { headline: 'Revenue model extends beyond software', detail: 'Implementation services represent 30% of revenue, which may compress margins and complicate scalability story.', severity: 'high' },
        { headline: 'ARR modest for Series A valuation', detail: '$420K ARR at $32M pre-money implies a 76x ARR multiple; high relative to comparable climate SaaS rounds.', severity: 'medium' },
      ],
      rawHighlights: [
        'Strong regulatory tailwind — SEC climate disclosure rules create immediate demand',
        'Founder with 10 years at Honeywell provides rare enterprise credibility',
        '3 signed LOIs suggest strong near-term ARR growth',
        'Services revenue complicates the SaaS narrative',
        'Valuation multiple is aggressive at $420K ARR',
        'Integration depth (ERP + IoT) creates switching costs but also long sales cycles',
      ],
    },
    thesisScores: [
      { criterion: 'Market Size', score: 8, reason: 'Credible $18B TAM cited with BloombergNEF data; regulatory drivers add urgency.', weight: 20 },
      { criterion: 'Team Strength', score: 8, reason: 'Honeywell + Palantir pedigree is directly relevant to the industrial customer base.', weight: 25 },
      { criterion: 'Traction', score: 6, reason: '$420K ARR is early for Series A; 3 LOIs are encouraging but not yet contracted.', weight: 20 },
      { criterion: 'Stage Fit', score: 7, reason: 'Series A stage aligns with mandate, but valuation multiple is stretched.', weight: 20 },
      { criterion: 'Sector Match', score: 9, reason: 'Climate tech is a primary thesis vertical with strong conviction.', weight: 15 },
    ],
    redFlags: [
      { headline: 'Revenue model extends beyond software', detail: 'Implementation services represent 30% of revenue, which may compress margins and complicate scalability story.', severity: 'high' },
      { headline: 'ARR modest for Series A valuation', detail: '$420K ARR at $32M pre-money implies a 76x ARR multiple; high relative to comparable climate SaaS rounds.', severity: 'medium' },
    ],
  },
  {
    id: 'deal-tempo-003',
    analystId: 'alex@meridiancap.com',
    companyName: 'Tempo',
    oneLiner: 'Scheduling infrastructure for outpatient mental health clinics',
    stage: 'Pre-seed',
    sector: 'Healthtech',
    geography: 'San Francisco, CA',
    overallThesisScore: 6.1,
    pipelineStatus: 'new',
    analystNotes: '',
    memoContent: null,
    aiDetection: tempoAIDetection,
    createdAt: '2026-05-09T08:00:00Z',
    updatedAt: '2026-05-09T08:00:00Z',
    analysis: {
      companyName: 'Tempo',
      oneLiner: 'Scheduling infrastructure for outpatient mental health clinics',
      problem: 'Outpatient mental health clinics lose an estimated 25% of scheduled appointments to no-shows and cancellations. Existing scheduling tools are generic and fail to account for the specific dynamics of mental health care, including recurring appointments and insurance coordination.',
      solution: 'Tempo provides a purpose-built scheduling and waitlist management platform for mental health clinics, with automated reminders, intelligent waitlist backfill, and insurance eligibility verification integrated into the booking flow.',
      businessModel: 'Not explicitly stated. Likely SaaS by seat or per-location pricing based on comparable products, but no pricing details provided in deck.',
      stage: 'Pre-seed',
      sector: 'Healthtech',
      geography: 'San Francisco, CA',
      founded: '2025',
      website: null,
      market: {
        tam: '$12B',
        sam: null,
        som: null,
        framing: 'Company cites behavioral health market size broadly but does not provide a narrowed SAM/SOM estimate.',
      },
      traction: [
        { metric: 'Pilot Clinics', value: '3' },
        { metric: 'Revenue', value: 'None stated' },
      ],
      team: [
        { name: 'Jordan Miles', role: 'CEO & Founder', background: 'Former product manager at One Medical. No stated co-founder or healthcare operator on the team.' },
      ],
      askingAmount: '$1.2M',
      valuation: '$6M pre-money',
      redFlags: [
        { headline: 'Solo founder, no co-founder', detail: 'Company is led by a single founder with no stated co-founder, raising execution and resilience concerns.', severity: 'high' },
        { headline: 'No healthcare operator on team', detail: 'Founding team lacks clinical operations experience, which may slow enterprise sales into health system buyers.', severity: 'high' },
        { headline: 'No revenue model stated in deck', detail: 'Deck does not specify pricing structure, unit economics, or monetization timeline.', severity: 'medium' },
      ],
      rawHighlights: [
        'Real operational pain point with $12B addressable market',
        'Mental health scheduling is underserved by existing tools',
        'Solo founder is a structural risk at pre-seed stage',
        'No stated revenue model makes financial projections impossible to evaluate',
        '3 pilot clinics is very early; no revenue data',
        'One Medical background is relevant but not deep clinical operations',
      ],
    },
    thesisScores: [
      { criterion: 'Market Size', score: 7, reason: '$12B market cited but no SAM/SOM provided; difficult to assess realistic capture.', weight: 20 },
      { criterion: 'Team Strength', score: 4, reason: 'Solo founder with product background; no clinical operator or co-founder.', weight: 25 },
      { criterion: 'Traction', score: 3, reason: '3 pilot clinics with no stated revenue is minimal for investment consideration.', weight: 20 },
      { criterion: 'Stage Fit', score: 8, reason: 'Pre-seed stage and $1.2M ask aligns with fund entry criteria.', weight: 20 },
      { criterion: 'Sector Match', score: 7, reason: 'Healthtech is within thesis scope, though mental health vertical is not a primary focus area.', weight: 15 },
    ],
    redFlags: [
      { headline: 'Solo founder, no co-founder', detail: 'Company is led by a single founder with no stated co-founder, raising execution and resilience concerns.', severity: 'high' },
      { headline: 'No healthcare operator on team', detail: 'Founding team lacks clinical operations experience, which may slow enterprise sales into health system buyers.', severity: 'high' },
      { headline: 'No revenue model stated in deck', detail: 'Deck does not specify pricing structure, unit economics, or monetization timeline.', severity: 'medium' },
    ],
  },
  {
    id: 'deal-conduit-004',
    analystId: 'alex@meridiancap.com',
    companyName: 'Conduit',
    oneLiner: 'API infrastructure for real-time cross-border B2B payments',
    stage: 'Series A',
    sector: 'Fintech',
    geography: 'Chicago, IL',
    overallThesisScore: 9.1,
    pipelineStatus: 'active_diligence',
    analystNotes: 'Top priority. Diligence calls scheduled with 3 enterprise customers. Legal reviewing term sheet language. Target close by end of month.',
    memoContent: null,
    aiDetection: conduitAIDetection,
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-05-10T16:00:00Z',
    analysis: {
      companyName: 'Conduit',
      oneLiner: 'API infrastructure for real-time cross-border B2B payments',
      problem: 'Cross-border B2B payments remain slow (2-5 business days), expensive (2-4% fees), and opaque. Enterprise treasury teams lack real-time visibility into payment status, creating reconciliation challenges and working capital inefficiencies.',
      solution: 'Conduit provides a developer-first API layer that routes cross-border payments through an optimized network of local payment rails, delivering same-day settlement in 40+ countries at sub-1% fees with real-time tracking.',
      businessModel: 'Transaction fees (basis points on payment volume) plus a monthly platform fee for API access. Current blended take rate approximately 0.6% of payment volume.',
      stage: 'Series A',
      sector: 'Fintech',
      geography: 'Chicago, IL',
      founded: '2022',
      website: 'conduit.finance',
      market: {
        tam: '$150B',
        sam: '$22B',
        som: '$1.1B',
        framing: 'Company targets mid-market and enterprise B2B cross-border flows, citing World Bank and McKinsey data on global payment volume.',
      },
      traction: [
        { metric: 'ARR', value: '$1.2M' },
        { metric: 'Monthly Volume', value: '$40M' },
        { metric: 'Gross Margin', value: '65%' },
        { metric: 'Customers', value: '28' },
        { metric: 'Countries Supported', value: '42' },
        { metric: 'Avg Transaction Size', value: '$18,500' },
        { metric: 'MoM Growth', value: '22%' },
      ],
      team: [
        { name: 'Ana Reyes', role: 'CEO & Co-founder', background: 'Former Head of International Payments at JPMorgan Chase; 12 years in cross-border transaction infrastructure.' },
        { name: 'Kevin Osei', role: 'CTO & Co-founder', background: 'Ex-principal engineer at Ripple, built distributed settlement systems processing $2B+ annually.' },
        { name: 'Rachel Huang', role: 'CFO', background: 'Former CFO at a Series B fintech; CPA with Big 4 background in financial services.' },
      ],
      askingAmount: '$12M',
      valuation: '$55M pre-money',
      redFlags: [],
      rawHighlights: [
        'Processing $40M/month with 65% gross margin is exceptional for payments infrastructure',
        '$1.2M ARR growing 22% MoM — strong trajectory',
        'Founding team is among the strongest seen this year in fintech',
        '42 country coverage is a significant moat for enterprise buyers',
        'Zero material red flags identified in deck',
        'Valuation at $55M pre-money is reasonable for this traction profile',
      ],
    },
    thesisScores: [
      { criterion: 'Market Size', score: 10, reason: '$150B TAM in cross-border payments backed by World Bank and McKinsey data; one of the largest addressable markets in fintech.', weight: 20 },
      { criterion: 'Team Strength', score: 10, reason: 'JPMorgan + Ripple founding team with 12-year domain expert CEO is rare and directly defensible.', weight: 25 },
      { criterion: 'Traction', score: 9, reason: '$40M monthly volume, 65% gross margin, and 22% MoM growth at Series A is exceptional.', weight: 20 },
      { criterion: 'Stage Fit', score: 8, reason: 'Series A at this traction level represents strong risk-adjusted entry.', weight: 20 },
      { criterion: 'Sector Match', score: 10, reason: 'Fintech infrastructure is the highest-conviction thesis vertical.', weight: 15 },
    ],
    redFlags: [],
  },
  {
    id: 'deal-canopy-005',
    analystId: 'alex@meridiancap.com',
    companyName: 'Canopy',
    oneLiner: 'Subscription hydroponic growing kits for urban apartments',
    stage: 'Seed',
    sector: 'Consumer',
    geography: 'Los Angeles, CA',
    overallThesisScore: 3.8,
    pipelineStatus: 'passed',
    analystNotes: 'Passed. Consumer hardware with no unit economics disclosed. Outside sector focus.',
    memoContent: null,
    aiDetection: canopyAIDetection,
    createdAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-04-18T11:00:00Z',
    analysis: {
      companyName: 'Canopy',
      oneLiner: 'Subscription hydroponic growing kits for urban apartments',
      problem: 'Urban consumers lack access to fresh, locally grown produce and have limited space for traditional gardening. Existing hydroponic kits are expensive, complex to maintain, and require horticultural expertise.',
      solution: 'Canopy offers a compact, app-connected hydroponic growing system with monthly seed pod subscriptions, automated nutrient delivery, and guided growing programs accessible via mobile app.',
      businessModel: 'Hardware sale ($299 kit) plus recurring seed pod subscription ($29/month). Gross margin on hardware is estimated at 25%, subscription at 65%.',
      stage: 'Seed',
      sector: 'Consumer',
      geography: 'Los Angeles, CA',
      founded: '2024',
      website: 'canopygrows.com',
      market: {
        tam: '$8B',
        sam: null,
        som: null,
        framing: 'Company references indoor gardening and urban agriculture market broadly. No third-party source cited.',
      },
      traction: [
        { metric: 'Kickstarter Backers', value: '1,200' },
        { metric: 'Pre-orders', value: '$180K' },
        { metric: 'Revenue', value: 'None (pre-launch)' },
      ],
      team: [
        { name: 'Matt Torres', role: 'CEO & Co-founder', background: 'Former industrial designer at IDEO; first consumer hardware company.' },
        { name: 'Lisa Chen', role: 'CPO & Co-founder', background: 'Former growth lead at a DTC subscription box company.' },
      ],
      askingAmount: '$2M',
      valuation: '$9M pre-money',
      redFlags: [
        { headline: 'Consumer market outside sector focus', detail: 'DTC consumer hardware is not within the firm\'s stated sector focus of B2B SaaS, Fintech, and Climate Tech.', severity: 'high' },
        { headline: 'No unit economics provided', detail: 'Deck does not include customer acquisition cost, LTV, or payback period for the hardware + subscription model.', severity: 'high' },
        { headline: 'Pre-revenue company seeking Seed valuation', detail: 'No actual revenue; 1,200 Kickstarter backers as primary traction signal is insufficient for $9M pre-money.', severity: 'medium' },
        { headline: 'Hardware margin at 25% is thin', detail: 'Consumer hardware at 25% gross margin leaves limited room for distribution and support costs.', severity: 'medium' },
      ],
      rawHighlights: [
        'Consumer hardware is outside thesis sector focus',
        '1,200 Kickstarter backers shows demand signal but no revenue',
        'Hardware + subscription model creates unit economics complexity',
        '25% hardware gross margin is thin for consumer product',
        'Team lacks CPG or mass retail distribution experience',
        'Market sizing unsourced and broad',
      ],
    },
    thesisScores: [
      { criterion: 'Market Size', score: 5, reason: '$8B market claim lacks third-party sourcing; SAM/SOM not provided.', weight: 20 },
      { criterion: 'Team Strength', score: 4, reason: 'Design and growth background is relevant but neither founder has scaled hardware or CPG distribution.', weight: 25 },
      { criterion: 'Traction', score: 2, reason: 'Pre-revenue with Kickstarter backers as primary signal; insufficient for Seed stage.', weight: 20 },
      { criterion: 'Stage Fit', score: 5, reason: 'Seed stage aligns with mandate but hardware business model is outside core thesis.', weight: 20 },
      { criterion: 'Sector Match', score: 2, reason: 'Consumer DTC hardware is outside all stated sector focus areas.', weight: 15 },
    ],
    redFlags: [
      { headline: 'Consumer market outside sector focus', detail: 'DTC consumer hardware is not within the firm\'s stated sector focus of B2B SaaS, Fintech, and Climate Tech.', severity: 'high' },
      { headline: 'No unit economics provided', detail: 'Deck does not include customer acquisition cost, LTV, or payback period for the hardware + subscription model.', severity: 'high' },
      { headline: 'Pre-revenue company seeking Seed valuation', detail: 'No actual revenue; 1,200 Kickstarter backers as primary traction signal is insufficient for $9M pre-money.', severity: 'medium' },
      { headline: 'Hardware margin at 25% is thin', detail: 'Consumer hardware at 25% gross margin leaves limited room for distribution and support costs.', severity: 'medium' },
    ],
  },
];

export const mockThesisConfig: ThesisConfig = {
  id: 'thesis-meridian-001',
  analystId: 'alex@meridiancap.com',
  firmName: 'Meridian Capital',
  focusStages: ['Pre-seed', 'Seed', 'Series A'],
  targetSectors: ['B2B SaaS', 'Fintech', 'Climate Tech', 'Healthtech', 'Infrastructure'],
  checkSizeMin: 500000,
  checkSizeMax: 15000000,
  geography: ['North America', 'Europe'],
  criteria: [
    { name: 'Market Size', description: 'Is the total addressable market large enough to support a venture-scale outcome?', weight: 20 },
    { name: 'Team Strength', description: 'Does the founding team have relevant domain expertise and the ability to execute?', weight: 25 },
    { name: 'Traction', description: 'Is there evidence of product-market fit or meaningful early adoption?', weight: 20 },
    { name: 'Stage Fit', description: 'Does the deal stage and check size align with our investment mandate?', weight: 20 },
    { name: 'Sector Match', description: 'Is this company within our target sector verticals?', weight: 15 },
  ],
  autoFlags: {
    noRevenueModel: true,
    soloFounder: true,
    noTractionMetrics: true,
    unsubstantiatedMarket: true,
    outsideStage: false,
  },
};

export const mockAnalyst = {
  firmName: 'Meridian Capital',
  analystName: 'Alex Chen',
  email: 'alex@meridiancap.com',
};
